version: 2

project_name: aws-ide

before:
  hooks:
    - go work sync
    - go mod tidy -C apps/jupyter
    - go mod tidy -C apps/rstudio
    - go mod tidy -C pkg

builds:
  - id: aws-jupyter
    main: ./apps/jupyter/cmd/aws-jupyter
    binary: aws-jupyter
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: aws-rstudio
    main: ./apps/rstudio/cmd/aws-rstudio
    binary: aws-rstudio
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: jupyter
    builds:
      - aws-jupyter
    name_template: >-
      aws-jupyter_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - apps/jupyter/README.md
      - apps/jupyter/environments/*.yaml
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: rstudio
    builds:
      - aws-rstudio
    name_template: >-
      aws-rstudio_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - apps/rstudio/README.md
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: scttfrdmn
    name: aws-ide
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    AWS IDE is a monorepo containing multiple cloud-based IDE launchers:
    - **aws-jupyter**: Launch Jupyter Lab instances on AWS EC2
    - **aws-rstudio**: Launch RStudio Server instances on AWS EC2

    Both tools share infrastructure from the `pkg/` module for consistent behavior.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

    See the [CHANGELOG](https://github.com/scttfrdmn/aws-ide/blob/{{ .Tag }}/CHANGELOG.md) for detailed release notes.

# Homebrew formulas for both tools
# Note: 'brews' is the correct field name for Homebrew tap formulas
brews:
  - name: aws-jupyter
    ids:
      - jupyter
    repository:
      owner: scttfrdmn
      name: homebrew-tap
    homepage: https://github.com/scttfrdmn/aws-ide
    description: CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors
    license: Apache-2.0
    install: |
      bin.install "aws-jupyter"

      # Install environment templates
      pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
      (pkgshare/"environments").mkpath
      Dir["apps/jupyter/environments/*.yaml"].each do |env|
        (pkgshare/"environments").install env
      end
    test: |
      system "#{bin}/aws-jupyter", "--version"

  - name: aws-rstudio
    ids:
      - rstudio
    repository:
      owner: scttfrdmn
      name: homebrew-tap
    homepage: https://github.com/scttfrdmn/aws-ide
    description: CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors
    license: Apache-2.0
    install: |
      bin.install "aws-rstudio"
    test: |
      system "#{bin}/aws-rstudio", "--version"
