version: 2

project_name: lens

before:
  hooks:
    - go work sync
    - go mod tidy -C apps/jupyter
    - go mod tidy -C apps/rstudio
    - go mod tidy -C pkg

builds:
  - id: lens-jupyter
    main: ./apps/jupyter/cmd/lens-jupyter
    binary: lens-jupyter
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: lens-rstudio
    main: ./apps/rstudio/cmd/lens-rstudio
    binary: lens-rstudio
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: lens-vscode
    main: ./apps/vscode/cmd/lens-vscode
    binary: lens-vscode
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: jupyter
    builds:
      - lens-jupyter
    name_template: >-
      lens-jupyter_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - apps/jupyter/README.md
      - apps/jupyter/environments/*.yaml
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: rstudio
    builds:
      - lens-rstudio
    name_template: >-
      lens-rstudio_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - apps/rstudio/README.md
      - apps/rstudio/environments/*.yaml
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: vscode
    builds:
      - lens-vscode
    name_template: >-
      lens-vscode_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - apps/vscode/README.md
      - apps/vscode/environments/*.yaml
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: scttfrdmn
    name: lens
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    Lens is a monorepo containing multiple cloud-based IDE launchers:
    - **lens-jupyter**: Launch Jupyter Lab instances on AWS EC2 (Production)
    - **lens-rstudio**: Launch RStudio Server instances on AWS EC2 (Production)
    - **lens-vscode**: Launch VSCode Server instances on AWS EC2 (Beta)

    All tools share infrastructure from the `pkg/` module for consistent behavior.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

    See the [CHANGELOG](https://github.com/scttfrdmn/lens/blob/{{ .Tag }}/CHANGELOG.md) for detailed release notes.

# Homebrew formulas for both tools
# Note: 'brews' is the correct field name for Homebrew tap formulas
brews:
  - name: lens-jupyter
    ids:
      - jupyter
    repository:
      owner: scttfrdmn
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors
    license: Apache-2.0
    install: |
      bin.install "lens-jupyter"

      # Install environment templates
      pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
      (pkgshare/"environments").mkpath
      Dir["apps/jupyter/environments/*.yaml"].each do |env|
        (pkgshare/"environments").install env
      end
    test: |
      system "#{bin}/lens-jupyter", "--version"

  - name: lens-rstudio
    ids:
      - rstudio
    repository:
      owner: scttfrdmn
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors
    license: Apache-2.0
    install: |
      bin.install "lens-rstudio"

      # Install environment templates
      pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
      (pkgshare/"environments").mkpath
      Dir["apps/rstudio/environments/*.yaml"].each do |env|
        (pkgshare/"environments").install env
      end
    test: |
      system "#{bin}/lens-rstudio", "--version"

  - name: lens-vscode
    ids:
      - vscode
    repository:
      owner: scttfrdmn
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)
    license: Apache-2.0
    install: |
      bin.install "lens-vscode"

      # Install environment templates
      pkgshare.install Dir["apps/vscode/environments/*.yaml"]
      (pkgshare/"environments").mkpath
      Dir["apps/vscode/environments/*.yaml"].each do |env|
        (pkgshare/"environments").install env
      end
    test: |
      system "#{bin}/lens-vscode", "--version"

# Scoop manifests for Windows
scoops:
  - name: lens-jupyter
    ids:
      - jupyter
    repository:
      owner: scttfrdmn
      name: scoop-bucket
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors
    license: Apache-2.0

  - name: lens-rstudio
    ids:
      - rstudio
    repository:
      owner: scttfrdmn
      name: scoop-bucket
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors
    license: Apache-2.0

  - name: lens-vscode
    ids:
      - vscode
    repository:
      owner: scttfrdmn
      name: scoop-bucket
    homepage: https://github.com/scttfrdmn/lens
    description: CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)
    license: Apache-2.0

# Linux packages (deb and rpm)
nfpms:
  - id: jupyter-packages
    builds:
      - lens-jupyter
    package_name: lens-jupyter
    vendor: Scott Friedman
    homepage: https://github.com/scttfrdmn/lens
    maintainer: Scott Friedman <scttfrdmn@users.noreply.github.com>
    description: CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: apps/jupyter/environments/*.yaml
        dst: /usr/share/lens-jupyter/environments/

  - id: rstudio-packages
    builds:
      - lens-rstudio
    package_name: lens-rstudio
    vendor: Scott Friedman
    homepage: https://github.com/scttfrdmn/lens
    maintainer: Scott Friedman <scttfrdmn@users.noreply.github.com>
    description: CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: apps/rstudio/environments/*.yaml
        dst: /usr/share/lens-rstudio/environments/

  - id: vscode-packages
    builds:
      - lens-vscode
    package_name: lens-vscode
    vendor: Scott Friedman
    homepage: https://github.com/scttfrdmn/lens
    maintainer: Scott Friedman <scttfrdmn@users.noreply.github.com>
    description: CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: apps/vscode/environments/*.yaml
        dst: /usr/share/lens-vscode/environments/
