name: ✨ Feature Request
description: Suggest a new feature or enhancement for AWS IDE
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: dropdown
    id: persona
    attributes:
      label: Who is this feature for?
      description: Select the primary user persona(s) who would benefit
      multiple: true
      options:
        - Solo Researcher
        - Research Lab (PI + Team)
        - Data Scientist
        - Graduate Student
        - Course Instructor/TA
        - Workshop Facilitator
        - IT Administrator
        - Other
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Which app(s) would this affect?
      description: Select all that apply
      multiple: true
      options:
        - aws-jupyter
        - aws-rstudio
        - aws-vscode
        - All apps
        - Shared infrastructure (pkg/)
    validations:
      required: true

  - type: dropdown
    id: use_case
    attributes:
      label: Research Use Case
      description: What type of research work would this support?
      multiple: true
      options:
        - Data Analysis
        - Machine Learning / AI
        - Bioinformatics / Genomics
        - Statistical Modeling
        - Scientific Computing
        - Data Visualization
        - Collaborative Research
        - Teaching / Workshops
        - Cost Optimization
        - Reproducible Research
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or pain point this feature would address
      placeholder: |
        As a [persona], I want to [goal] so that I can [benefit].
        
        Currently, [describe the challenge or limitation]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        Add a new command/flag/feature that...
        
        Example usage:
        \`\`\`bash
        aws-jupyter launch --new-feature ...
        \`\`\`
        
        This would allow users to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        Currently I work around this by...
        OR
        I haven't found a good workaround

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Impact
      description: How would this feature change your typical workflow?
      placeholder: |
        **Current Workflow:**
        1. [step]
        2. [step]
        3. [step]
        
        **With This Feature:**
        1. [simplified step]
        2. [benefit]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your work?
      options:
        - Critical (blocking important work)
        - High (significant impact on productivity)
        - Medium (nice to have, noticeable improvement)
        - Low (minor convenience)
    validations:
      required: true

  - type: checkboxes
    id: breaking_change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing functionality?
      options:
        - label: This feature would require breaking changes
        - label: I'm willing to migrate my existing setup if needed

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, examples, or screenshots that would help explain this feature
      placeholder: |
        Related issues/PRs: #123
        Example from other tools: [tool name]
        Screenshots/mockups: [attach images]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
