name: ✨ Feature Request
description: Suggest a new feature or enhancement for Lens
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: dropdown
    id: persona
    attributes:
      label: Who is this feature for?
      description: |
        Select the primary user persona(s) who would benefit from this feature.
        See [Persona Walkthroughs](https://github.com/scttfrdmn/lens/tree/main/docs/USER_SCENARIOS) for detailed descriptions.
      multiple: true
      options:
        - Solo Researcher (individual, limited budget, simple needs)
        - Graduate Student (PhD/Masters, advisor oversight, cost-sensitive)
        - Lab PI (managing 5-10 researchers, budget oversight, reproducibility)
        - Course Instructor (teaching 30+ students, consistent environments)
        - Research Computing Manager (institutional, 100+ researchers, compliance)
        - Other (please describe in Additional Context)
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Roadmap Phase
      description: |
        Which development phase does this feature align with? See [ROADMAP.md](https://github.com/scttfrdmn/lens/blob/main/ROADMAP.md) for phase details.
      options:
        - "v0.7.0 - User Experience & Accessibility"
        - "v0.8.0 - Additional Research Tools"
        - "v0.9.0 - Package Managers & Reproducible Environments"
        - "v0.10.0 - Collaboration Features"
        - "v0.11.0 - Cost Management for Labs"
        - "v1.0.0 - Production Ready for Academia"
        - "Backlog - Future Consideration"
        - "Not Sure"
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Which app(s) would this affect?
      description: Select all that apply
      multiple: true
      options:
        - lens-jupyter
        - lens-rstudio
        - lens-vscode
        - All apps
        - Shared infrastructure (pkg/)
    validations:
      required: true

  - type: dropdown
    id: use_case
    attributes:
      label: Research Use Case
      description: What type of research work would this support?
      multiple: true
      options:
        - Data Analysis
        - Machine Learning / AI
        - Bioinformatics / Genomics
        - Statistical Modeling
        - Scientific Computing
        - Data Visualization
        - Collaborative Research
        - Teaching / Workshops
        - Cost Optimization
        - Reproducible Research
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Describe the problem or pain point this feature would address.
        Use "As a [persona], I need [action] because [reason]" format.
        See [USER_REQUIREMENTS.md](https://github.com/scttfrdmn/lens/blob/main/docs/USER_REQUIREMENTS.md) for examples.
      placeholder: |
        As a [Solo Researcher/Graduate Student/Lab PI/Instructor/Manager], I need to [action] because [reason].

        **Current Pain Point:**
        [Describe the current challenge or limitation with quantified impact if possible]

        **Success Metric:**
        [How will you measure if this feature solves the problem?]

        **Related Persona Walkthrough:**
        [Optional: Link to relevant USER_SCENARIOS walkthrough, e.g., "docs/USER_SCENARIOS/01_SOLO_RESEARCHER_WALKTHROUGH.md - Pain Point #2"]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        Add a new command/flag/feature that...
        
        Example usage:
        \`\`\`bash
        lens-jupyter launch --new-feature ...
        \`\`\`
        
        This would allow users to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        Currently I work around this by...
        OR
        I haven't found a good workaround

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Impact
      description: How would this feature change your typical workflow?
      placeholder: |
        **Current Workflow:**
        1. [step]
        2. [step]
        3. [step]
        
        **With This Feature:**
        1. [simplified step]
        2. [benefit]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your work?
      options:
        - Critical (blocking important work)
        - High (significant impact on productivity)
        - Medium (nice to have, noticeable improvement)
        - Low (minor convenience)
    validations:
      required: true

  - type: checkboxes
    id: breaking_change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing functionality?
      options:
        - label: This feature would require breaking changes
        - label: I'm willing to migrate my existing setup if needed

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, examples, or screenshots that would help explain this feature
      placeholder: |
        Related issues/PRs: #123
        Example from other tools: [tool name]
        Screenshots/mockups: [attach images]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
