name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22', '1.23']
        module: ['pkg', 'jupyter', 'rstudio', 'vscode']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies (pkg)
        if: matrix.module == 'pkg'
        run: |
          cd pkg
          go mod download

      - name: Get dependencies (jupyter)
        if: matrix.module == 'jupyter'
        run: |
          cd apps/jupyter
          go mod download

      - name: Get dependencies (rstudio)
        if: matrix.module == 'rstudio'
        run: |
          cd apps/rstudio
          go mod download

      - name: Run tests (pkg)
        if: matrix.module == 'pkg'
        run: |
          cd pkg
          go test -v -race ./...

      - name: Run tests (jupyter)
        if: matrix.module == 'jupyter'
        run: |
          cd apps/jupyter
          go test -v -race ./...

      - name: Run tests (rstudio)
        if: matrix.module == 'rstudio'
        run: |
          cd apps/rstudio
          go test -v -race ./... || echo "No tests yet"

      - name: Get dependencies (vscode)
        if: matrix.module == 'vscode'
        run: |
          cd apps/vscode
          go mod download

      - name: Run tests (vscode)
        if: matrix.module == 'vscode'
        run: |
          cd apps/vscode
          go test -v -race ./... || echo "No tests yet"

      # Coverage upload disabled - codecov integration can be re-enabled later if needed
      # - name: Upload coverage to Codecov
      #   if: matrix.go == '1.22'
      #   uses: codecov/codecov-action@v4
      #   with:
      #     file: ./${{ matrix.module == 'pkg' && 'pkg' || format('apps/{0}', matrix.module) }}/coverage.out
      #     flags: ${{ matrix.module }}
      #     fail_ci_if_error: false

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run gofmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files need formatting:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run go vet (pkg)
        run: |
          cd pkg
          go vet ./...

      - name: Run go vet (jupyter)
        run: |
          cd apps/jupyter
          go vet ./...

      - name: Run go vet (rstudio)
        run: |
          cd apps/rstudio
          go vet ./...

      - name: Run go vet (vscode)
        run: |
          cd apps/vscode
          go vet ./...

      - name: Run golangci-lint (pkg)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: pkg
          args: --timeout=5m

      - name: Run golangci-lint (jupyter)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: apps/jupyter
          args: --timeout=5m

      - name: Run golangci-lint (rstudio)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: apps/rstudio
          args: --timeout=5m

      - name: Run golangci-lint (vscode)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: apps/vscode
          args: --timeout=5m

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: ec2,iam,ssm
          DEBUG: 1
          DOCKER_HOST: unix:///var/run/docker.sock
        ports:
          - 4566:4566
        options: >-
          --health-cmd "awslocal ec2 describe-regions || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          timeout 60 bash -c 'until curl -s http://localhost:4566/_localstack/health | grep -q "\"ec2\": \"available\""; do sleep 2; done'
          echo "LocalStack is ready"

      - name: Run integration tests (pkg)
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd pkg
          go test -v -tags=integration -timeout 10m ./...

      - name: Run integration tests (jupyter)
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd apps/jupyter
          go test -v -tags=integration -timeout 10m ./... || echo "No integration tests yet"

      - name: Run integration tests (rstudio)
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd apps/rstudio
          go test -v -tags=integration -timeout 10m ./... || echo "No integration tests yet"

      - name: Run integration tests (vscode)
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd apps/vscode
          go test -v -tags=integration -timeout 10m ./... || echo "No integration tests yet"

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['jupyter', 'rstudio', 'vscode']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build ${{ matrix.app }} binary
        run: |
          cd apps/${{ matrix.app }}
          go build -v ./cmd/aws-${{ matrix.app }}

      - name: Test ${{ matrix.app }} binary help
        run: |
          cd apps/${{ matrix.app }}
          ./aws-${{ matrix.app }} --help

      - name: Test ${{ matrix.app }} binary version
        run: |
          cd apps/${{ matrix.app }}
          ./aws-${{ matrix.app }} --version
