name: Project Automation

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        if: github.event_name == 'issues'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/scttfrdmn/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR to project
        if: github.event_name == 'pull_request'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/scttfrdmn/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
